driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/car_4s?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
username=root
password=123456

initialSize=5
maxActive=20
minIdle=5
maxWait=30000

validationQuery=SELECT 1
testWhileIdle=true
testOnBorrow=false
testOnReturn=false

timeBetweenEvictionRunsMillis=60000
minEvictableIdleTimeMillis=300000

poolPreparedStatements=true
maxPoolPreparedStatementPerConnectionSize=20
